version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    networks:
      - mynetwork
    volumes:
      - /Users/vishal/Sync/work/master/database/master.db:/Users/vishal/Sync/work/master/database/master.db
    restart: unless-stopped
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase 
      MB_DB_PORT: 5432 # Change this to the port your local PostgreSQL is running on
      MB_DB_USER: metabase
      MB_DB_PASS: 
      MB_DB_HOST: 192.168.1.230 # Use this to connect to the host machine
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge
